AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A starter AWS Lambda function.
Parameters:
  IdentityNameParameter:
    Type: String
Resources:
  helloworldpython3:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: s3://pointgenesis-cft/bf8463eab7cc3e41f4e4157665ac7d8a
      Description: A starter AWS Lambda function.
      MemorySize: 128
      Timeout: 3
      Policies:
      - SESSendBouncePolicy:
          IdentityName:
            Ref: IdentityNameParameter
